### ISSUE TITLE
[Art] - [New CB Tracker] Weapon and Character select 

### ISSUE THREAD

**Issue by ed3ath** [CryptoBlades/art-and-design#23]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

CB Tracker

### Describe the request and its requirements

Improve weapon and character select in Combat Simulator.

Currently we have this:
![image](https://user-images.githubusercontent.com/83283457/177292030-423a607c-9044-4424-bbf6-72cb8080f587.png)
![image](https://user-images.githubusercontent.com/83283457/177292239-fcfc02dd-b185-4dbd-8834-9d95ace2c856.png)

Weapon:
* Displays weapon data
* Favorite (On top)
* Filter (stars, element)

Character 
* Displays character data.

### Is your art request related to an existing issue? Please describe.

https://github.com/CryptoBlades/cb-tracker-mobile/issues/40

### Is there anything stopping this feature from being completed?

N/A

### Potential Deadline

anytime

### Describe alternatives you've considered

n/a

### Banner / Sprite assets

n/a
