### ISSUE TITLE
[Art] - [New CB Tracker] Desktop/Landscape version

### ISSUE THREAD

**Issue by ed3ath** [CryptoBlades/art-and-design#24]
### Prerequisites

- [X] I checked to make sure that this request has not already been filed
- [X] I'm reporting this information to the correct repository
- [X] I understand enough about this request to complete a comprehensive document

### Project

CB Tracker

### Describe the request and its requirements

Add Desktop/Landscape support for new cbtracker.

Current desktop/landscape version

![image](https://user-images.githubusercontent.com/83283457/177294012-5b5e3fe5-277e-4a7b-bce6-4cd3f62cea1b.png)
![image](https://user-images.githubusercontent.com/83283457/177294049-2aa4561f-1a24-41fc-92d3-53762e2bb1aa.png)
![image](https://user-images.githubusercontent.com/83283457/177294091-882b43e6-7634-4554-a545-940d0e0bdc2c.png)
![Uploading image.png…]()

### Is your art request related to an existing issue? Please describe.

https://github.com/CryptoBlades/cb-tracker-mobile/issues/39

### Is there anything stopping this feature from being completed?

N/A

### Potential Deadline

anytime

### Describe alternatives you've considered

N/A

### Banner / Sprite assets

N/A
